lucidworks/fusion-cloud-native

README.adoc
setup_f5_gke.sh

This PR:
- Adds an option to configure a GCP ingress with a a TLS certificate. This requires that a public DNS record can be created that points to the IP of the LB. GCP will then automatically provision a certificate.

Add option to use GCP managed certificates on proxy ingress

---

README.adoc

Let's consolidate the deployment docs into this README and let the docs site `include` it at build time.  I also added tags so that the site can `include` specific sections selectively.

DOCS-1654 - Sync the docs site with the README

---

setup_f5_gke.sh

This PR:
- Waits up to 50 seconds for the GCP Loadbalancer Ingress to have been assigned an IP before printing the message informing the user that they have to update the DNS record.

Ensure that the loadbalancer IP is available before printing the TLS message

---

customize_fusion_values.yaml.example
setup_f5_k8s.sh

This PR:
- Moves zookeeper configuration to be top level instead of being under `solr` this fixes an issue when installing fusion 5.0.2 where it would fail with:
```
Error: template: fusion/charts/solr/templates/_helpers.tpl:56:125: executing "solr.zookeeper-connection-string" at <$.Values.zookeeper.service.ports.client.port>: nil pointer evaluating interface {}.ports
```
- Adds a check for the `stable` helm repository, which is not enabled by default in helm v3

Add stable helm repo and move zookeeper to top leve configuration

---

setup_f5_eks.sh
setup_f5_gke.sh

This PR:
- Adds `path: /*` to the tls setup for `gke` 
- Adds `--profile "${AWS_ACCOUNT}"` when updating kubeconfig for eks clusters

Add missing --profile and add path to tls-setup

---

README.adoc
setup_f5_k8s.sh

This PR:
- Adds documentation for configuring the timeout for a GKE ingress
- Adds a note on configuration options to set if running with an `nginx` ingress controller
- Fixes an issue in purge with helm 3 where the purge would fail if not using the default namespace.

Add documentation for configuring timeouts in GKE and nginx ingress

---

README.adoc

Made a minor update to the README.adoc file so the Fusion 5 installation prerequisites can be included in the docs. (DOCS-2168)

DOCS-2168 Add Prerequisite Docs

---

customize_fusion_values.sh
example-values/prometheus-values.yaml
install_prom.sh
setup_f5_k8s.sh

This PR:
- Adds a stage to the prometheus server endpoint discovery to not scrape metrics from outside of the namespace that it is installed into when installed with the default prometheus values.

Add a source_label to drop all metrics outside of the installed namespace

---

example-values/prometheus-values.yaml

Added the `"^{NAMESPACE}$"` `keep` instruction to the scrape configs, so that they only keep metrics from that namespace.
The added `scrape_configs` are copy/pasted from the default helm chart's `values.yaml` so that we can add the `keep` property for each of the default scrape configs.

Ensure that other namespaces are scraped by Prometheus install

---

monitoring/grafana/README.adoc

Illustrating how to enable `kubeStateMetrics` so the `kube_metrics.json`-loaded dashboard shows data.

Add Prometheus config section to documentation for Grafana

---

setup_f5_aks.sh
setup_f5_eks.sh
setup_f5_gke.sh
setup_f5_k8s.sh

new logic:
1) if they don't pass `-n`  or `-r` at all, then default to `namespace=default` and `release=f5` as we have now, 
2) if they pass `-n` but no `-r` , then default the RELEASE to the value passed for -n

Default release to the namespace

---

customize_fusion_values.sh
install_prom.sh
setup_f5_gke.sh
setup_f5_k8s.sh

On Linux, calling `sed -i ''` leads to output like this:
```
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
sed: can't read : No such file or directory
```
Removing the space after `-i` seems to fix.

remove space after -i as it leads to errors on linux

---

README.adoc

Currently, we include a short snippet for upgrading Fusion 5 which is catered towards users on GKE. For the release of Fusion 5.1, we should include links to the upgrade instructions for each deployment option. This PR tags the upgrade instructions for EKS, AKS, GKE, and other K8s deployments. This will allow us to include the information in the docs. (DOCS-2234)

DOCS-2234 Fusion 5 Upgrade Docs

---

customize_fusion_values.sh
install_prom.sh
setup_f5_k8s.sh

Linux uses GNU sed while macOS uses BSD sed, this causes problems and creates unnecessary backup files in macOS clients.
@ian-thebridge-lucidworks has tested this in his local, no extra files were created.
I have tested it in my ubuntu local machine and it works.

APOLLO-23485: Add sed fixes depending on the OS

---

README.adoc

This PR updates the README file so the upgrade instructions are tagged separately from other instructions. The change will affect the docs site only. Now, upgrade instructions are separate from deployment instructions. (DOCS-2234)

DOCS-2234 F5 Upgrade Instructions

---

migrations/README.adoc

A small change to the wording to note that if the CRDs are already present in the cluster the temp namespace workaround doesn't need to be done.

Update migration guide to note that seldon CRDs may be present

---

migrations/README.adoc

This PR removes the tags the migration readme file so the duplicate table of contents will not appear in the documentation.

5.0.x to 5.1.x Quick Fix for Docs

---

customize_fusion_values.sh
customize_fusion_values.yaml.example

This PR changes how the `customize_fusion_values.sh` file determines the number of zookeeper replicas to run. Previously it used the same number of zookeeper nodes as `solr` nodes which caused problems if running with 2 solr nodes. It now:
- Uses a single zookeeper node if the number of `solr` nodes < 3
- Uses 3 zookeeper nodes otherwise, even with large fusion deployments we probably don't need more than 3 zookeepers running.

Change zookeeper replica handling

---

customize_fusion_values.sh
install_prom.sh
monitoring/grafana/dashboard_indexing_metrics.json
policy.json
setup_f5_eks.sh
setup_f5_gke.sh
setup_f5_k8s.sh
survival_guide/3_operations.adoc
update_commit_within_f5.sh
update_policy.sh
upgrade_fusion.sh.example

This PR:
- Changes the handling of installs so that now all installs of a cluster are done with the generated upgrade scripts. The `setup_f5_k8s.sh` script now calls this upgrade script and `install_prom.sh` to setup the clusters, and the cloud provider specific scripts create a cluster and then call the `setup_f5_k8s.sh` script.
More testing is required on the aks cluster setup before we merge this.

Consolidate scripts

---

monitoring/grafana/dashboard_indexing_metrics.json
monitoring/grafana/dashboard_jvm_metrics.json

This PR:
- Changes the jvm_metrics dashboard to use kubernetes_pod_name instead of kubernetes_pod
- Changes the indexing_metrics dashboard to use a relative time instead of absolute by default.

Change jvm metrics dashboard to use kubernetes_pod_name label

---

customize_fusion_values.yaml.example

Include fusion-jupyter in customize_fusion_values.yaml.example, set enabled to false .

Include jupyter in example yaml

---

survival_guide/3_operations.adoc

Update the Spark History Server guide with a missing `kubectl` command and more explanation of what is going on with the `gcloud` commands.

DOCS-2343 Spark History Server Updates

---

survival_guide/1_concepts.adoc

This PR updates the recommended Kubernetes version from 1.12 to 1.14 per https://lucidworks.slack.com/archives/CM63PKCS3/p1595519583196400. This change is reflected in the public docs.

Update Recommended K8S Version

---

README.adoc
setup_f5_eks.sh

Added support for internal ALBs, access to fusion was made from an instance located in the external subnet of the cluster.
Some other changes were applied:
- Minimal version for kubernetes was added.
- ALB policy was updated.
- A little change to the Readme was added.

APOLLO-25902 - added support for internal ALB

---

gke_scale_namespace_up_or_down.sh

This adds 'scaling-down' of Seldon deployments. This is a lie. It actually deletes all Seldon deployments within a namespace as `kubectl scale` is not apparently supported with the version of Seldon we're deploying in Fusion 5.0-5.2. When we upgrade to 1.2.x in Fusion 5.3, scaling should be supported, so I've included the eventual `kubectl scale` command as a comment for us to come back to later.

APOLLO-26331 Include Seldon deployments in scale-down

---

customize_fusion_values.yaml.example

with node selector and missing scrape annotations

APOLLO-27379: add missing config section for templating,

---

README.adoc

We have had a couple of tickets filed recently where customers noted they were confused where to find the Fusion UI after installation. This PR, alongside a PR to the docs repo, addresses this confusion. (DOCS-2766)

DOCS-2766 Fusion Host Confusion

---

example-values/resources.yaml
survival_guide/3_operations.adoc

Updates the example values to include Milvus and to place Argo / Seldon out of ml-model-service and as top-level services (as of 5.3)

APOLLO-27902 Update example values

---

example-values/replicas.yaml

APOLLO-28481: replica for plugins:
1. The base `connector-plugin-service` replicaCount must allays be 0.
2. The plugins replica count must be specify in `rpc-service` instead.

APOLLO-28481: replica for plugins

---

customize_fusion_values.yaml.example

Example of setting heap memory for pulsar broker and bookkeeper before Fusion 5.4.

APOLLO-28349 - Add pulsar memory configuration example

---

survival_guide/1_concepts.adoc

Updated fusion-cloud-native repo > survival_guide/1_concepts.adoc with generic version of K8s to use until the testing is completed.

DOCS-2492-k8s-version-change

---

survival_guide/2_planning.adoc

Add a short description as an optional step on how to import additional certificates into connector truststore. 
The certificates are saved as a secret and imported via init container.

APOLLO-28562: add info about additional connectors certificates

---

README.adoc

This tag allows us to pull in the info to a page on the docs site.

DOCS-1755: add kubectl tag

---

customize_fusion_values.yaml.example
example-values/resources.yaml
survival_guide/1_concepts.adoc

Config-sync is no longer valid for customers to use. It will be used internally.
modified:   customize_fusion_values.yaml.example
modified:   example-values/resources.yaml
modified:   survival_guide/1_concepts.adoc

DOCS-3225-remove-config-sync-references

---

README.adoc

[DOCS-3349](https://lucidworks.atlassian.net/browse/DOCS-3349)
It was reported the following error occurs:
error: Unexpected args: [fusion-namespace role.yaml]
README file was updated with the following workaround:
1. `k config set-context --current --namespace=$NAMESPACE ` 
2. `k apply -f role.yaml`
Additionally, instructions for creating a shell alias was moved from line 796 to line 85.

updated helm user permissions

---

monitoring/helm/fusion-monitoring-stack/README.md

Because the docs site imports this readme on one of our pages, need to fix the typo here so it displays properly on the site: https://doc.lucidworks.com/how-to/z9q3uw/helm-chart-for-preconfigured-monitoring-stack

Fix link formatting

---

README.adoc

DOCS-5347 Updated incorrect links and replaced the repo Survival Guide links with the links in the fusion-docs-site repo (we moved the survival guide into the fusion-docs-site repo and update it as needed).

DOCS-5347-update-incorrect-links
