setup_f5_aks.sh

Script is similar, it doesn't support multiple node pools yet, that's still in preview in AKS.

first commit of aks script

---

README.adoc

I made these minor changes as I bring the EKS installation information into the docs.

Made some minor changes to the EKS install information. (DOCS-1880)

---

setup_f5_aks.sh
setup_f5_eks.sh
setup_f5_gke.sh

This PR:
- Updates all the default versions for cloud providers to be `5.0.2-3`

Update default version for all providers

---

setup_f5_gke.sh

This PR:
- Removes the step that creates the GKE cluster
- Adds labels onto the namespaces to enforce ownership through the script, so a user cannot accidentally overwrite a release that was created by someone else.

Update script to not create GKE cluster and use labels on namespace to enforce owner

---

setup_f5_aks.sh

Improve wait loops for clusterissuer

Change tls to wait for clusterissuer to be correctly provisioned

---

README.adoc

Added a list of requied IAM policies for creating EKS clusters

Added required IAM policies for EKS

---

README.adoc

Added basic information about openshift

added openshift information

---

README.adoc

added eks permissions

---

customize_fusion_values.yaml.example

bumping the Solr version in example

bump Solr example.yaml version

---

gatling-qps/pom.xml
gatling-qps/src/test/scala/FusionQueryTraffic.scala

Use a background thread to refresh the global JWT vs. doing in the sim.

Gatling improvements

---

README.adoc
customize_fusion_values.yaml.example

This PR:
- Adds documentation for externalTrafficPolicy on api-gateway

Add documentation and default externalTrafficPolicy

---

additional_environments/setup_multinode_ekscluster.sh

This PR:
- Adds a script that will setup a multi node cluster with node_selectors from the survival guide.

Add setup script for multinode eks cluster

---

monitoring/grafana/README.adoc

Made some minor grammar and formatting issues to the Grafana readme file. Added a tag so the doc can be included in the docs.

DOCS-2181 Include Grafana Dashboard Info in Docs

---

README.adoc

This PR revises the content for the OTHER KUBERNETES PLATFORMS section. This information is being included in the documentation. (DOCS-2160)

DOCS-2160 Other K8s F5 Docs

---

README.adoc

Updated readme per https://jira.lucidworks.com/browse/APOLLO-22966 -> https://jira.lucidworks.com/browse/DOCS-2192

externalTrafficPolicy for existing values.yaml

---

setup_f5_aks.sh
setup_f5_eks.sh
setup_f5_gke.sh

This PR:
- Fixes the number of solr nodes deployed when called from then environment specific setup scripts.

Ensure num-solr and solr-disk-gb are passed to setup_f5_k8s.sh

---

customize_fusion_values.sh
setup_f5_k8s.sh
upgrade_fusion.sh.example

The scripts modifications were tested in a openshift cluster over EKS, it was created using openshift infrastructure installer.

APOLLO-24781 - Added openshift support to setup_k8s script

---

customize_fusion_values.sh
upgrade_fusion.sh.example

- fix the `sed` command usage in the scripts when using OS_TYPE=msys
- fix a syntax error in an if statement related to openshift

some fixes for openshift and windows

---

README.adoc
install_prom.sh
setup_f5_eks.sh
setup_f5_k8s.sh

Added some ingress information to the docs

APOLLO-24797 - added eks ingress options

---

survival_guide/3_operations.adoc

This PR:
- Updates the survival guide with the logging changes that are going into fusion 5.2

Update the survival guide with new logging options for fusion 5.2

---

customize_fusion_values.yaml.example

Adds Prometheus annotations for `job-launcher`, `job-rest-server`, and the `ml-service`.

APOLLO-25340 Add Prometheus annotations

---

setup_f5_k8s.sh

Given a little more time for AWS to provision the required nodes.

increased retries and timer for eks nodes

---

setup_f5_gke.sh

Instance type was updated for supporting new services.

APOLLO-26883-update-node

---

survival_guide/3_operations.adoc

GPU support for training in GKE example

Add GPU training instructions

---

README.adoc

updated README for 5.1.5 release

release-5.1.5

---

README.adoc
migrations/README.adoc

See also https://github.com/lucidworks/Fusion-docs/pull/1249

DOCS-2777 - upgrade to 5.3

---

survival_guide/1_concepts.adoc

Added description for connector-plugin-service.

APOLLO-28028: adds connector-plugin-service description

---

example-values/replicas.yaml

APOLLO-28481: add plugins replica count example

APOLLO-28481: add plugins replica count example

---

migrations/README.adoc

Updated the migrations/README.adoc file.

Docs 2926 clarify 52x to 53x upgrade

---

gke_scale_namespace_up_or_down.sh

updated scale script for 5.3.x components

CO-128 - fix-scale-script-53

---

survival_guide/1_concepts.adoc

https://lucidworks.slack.com/archives/C03118PB4/p1617112967035100?thread_ts=1617112132.034700&cid=C03118PB4

DOCS-3041: remove jwt link

---

survival_guide/3_operations.adoc

Modified the /fusion-cloud-native/survival_guide/3_operations.adoc

DOCS-3114-fix-gcp-launcher-step

---

README.adoc

Corrected to eks and added section per https://lucidworks.atlassian.net/browse/DOCS-2616.

DOCS-2616-fix-eks-param-in-shell

---

monitoring/grafana/dashboard-prometheus-benchmark.json

Added prometheus monitoring dashboard, obtained from Julius (Prometheus consultor) https://grafana.com/grafana/dashboards/12054

Added prometheus metrics dashboard

---

setup_f5_k8s.sh

This PR:
- Fixes purge option, adds checker for fusion-monitoring removal

FUS-71 - fix-purge-script

---

additional_environments/create_gke_cluster_node_pools.sh
setup_f5_gke.sh

This PR:
- Updates deprecated option for monitoring and logging
- Updates multi_az command to use the region instead of the zone.

FUS-691 - remove-stackdriver-flag

---

migrations/README.adoc

How to use https://github.com/lucidworks/fusion-packaging/pull/555

Solrconfig cache migration instruction

---

example-values/repository.yaml

Summary: Added repository.yaml which can be used for configuring Fusion to pull all of its images from a private repo

Fus-613 Private repo example yaml

---

example-values/repository5-5-x.yaml
example-values/repository5-6-x.yaml

Added versioning to the repository.yaml file to support multiple versions of the Fusion charts. 
1. Renamed repository.yaml to repository5-5-x.yaml 
2. Added repository5-6-0.yaml

FUS-1649 Added repository example for 5.6.0 and version existing version

---

README.adoc

Corrected 3 bullet points in the README file so it displays in the documentation correctly.

DOCS-4514-fix-bullet-point

---

README.adoc
example-values/resources.yaml

Fus 3079 custom plugin resources

FUS-3079 custom plugin resources

---

README.adoc

**Note: Do not merge this into main until after 5.9 is released!** (Engineering release is fine) The docs site includes content directly from this repository.
Added info on different resources per connector pod. Solves DOCS-4502.
I was testing something for our docs site, hence the separate branch.

DOCS-4502 FUS-3079 connector custom values

---

README.adoc

We received some feedback on the docs site on how this section (which we pull from this readme) is a little confusing. I rewrote this based on some suggestions in FUS-3315. I also updated some formatting to improve how it looks on the docs site.

Edits per DOCS-4344
